### PR TITLE
Map Jackson MismatchedInputException to BadRequestProblem

### LINKED ISSUE #167: Map jackson MismatchedInputException to BadRequestProblem
CBSS has recently migrated from openapi-generator-maven-plugin 7.1.0 to 7.11.0.

With https://github.com/OpenAPITools/openapi-generator/issues/19577, required="true" now gets added to the annotation attributes of setter / constructor for required properties. This means those required properties are now validated during Jackson unmarshalling, which happens BEFORE the bean validation.

2025-01-24 13:18:14,479 ERROR [org.jboss.resteasy.plugins.providers.jackson] (default task-1) {} RESTEASY-JACKSON000100: Not able to deserialize data provided: com.fasterxml.jackson.databind.exc.MismatchedInputException: Missing required creator property 'cbeNumber' (index 0)

We should map such exceptions to a proper BadRequestProblem.

### PR DESCRIPTION
**Pull request by jpraet**
(for missing required properties on request body)

Fixes #167.

### CODE REVIEW

File: belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/RoutingExceptionsHandler.java [hunk 1]
```diff
@@ -54,11 +61,24 @@ public ResponseEntity<Problem> handleMissingRequestHeaderException(MissingReques
...
     @ExceptionHandler(HttpMessageNotReadableException.class)
     public ResponseEntity<Problem> handleHttpMessageNotReadable(HttpMessageNotReadableException exception) {
-        LOGGER.info("Transforming HttpMessageNotReadableException " +
-                "to a BadRequestProblem with sanitized detail message", exception);
-        return ProblemMediaType.INSTANCE
-                .toResponse(new BadRequestProblem(InputValidationIssues.schemaViolation(InEnum.BODY, null, null,
-                        getSanitizedProblemDetailMessage(exception))));
+        if (exception.getCause() instanceof MismatchedInputException) {
+            MismatchedInputException mismatchedInputException = (MismatchedInputException) exception.getCause();
+            if (Arrays.stream(mismatchedInputException.getStackTrace())
```
Comment (jpraet) [inline belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/RoutingExceptionsHandler.java:66]: This is a bit ugly. Don't know if there's a cleaner way to do this?

Comment (jflabatBCSS) [reply belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/RoutingExceptionsHandler.java:66]: I don't find a better to do it neither. But let's hope we won't forget that constant in our code if one day the package gets migrated

**Review by jflabatBCSS — APPROVED** [review]
