### PR TITLE
Retrieve bean validation parameter names from Spring MVC / JAX-RS annotations

### LINKED ISSUE #96: Bug: parameter name not correctly retrieved from interface
Got the following response from a Spring Boot 3.3.3 application:
```
{
    "type": "urn:problem-type:belgif:badRequest",
    "href": "https://www.belgif.be/specification/rest/api-guide/problems/badRequest.html",
    "title": "Bad Request",
    "status": 400,
    "detail": "The input message is incorrect",
    "issues": [
        {
            "type": "urn:problem-type:belgif:input-validation:schemaViolation",
            "title": "Input value is invalid with respect to the schema",
            "detail": "must be greater than or equal to 197",
            "in": "path",
            "name": "arg0",
            "value": 160
        }
    ]
}
```
Parameter annotations are only present on the (generated) interface, not on the implementation (when adding annotation to the implementation, 'name' is filled in correctly). Probably something goes wrong in reading the annotations of the parent class / interface.

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #96

### CODE REVIEW

File: belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProvider.java [hunk 1]
```diff
@@ -0,0 +1,70 @@
...
+        return parameterNameCache.computeIfAbsent(constructor, this::getParameterNames);
+    }
+
+    @Override
+    public List<String> getParameterNames(Method method) {
+        return parameterNameCache.computeIfAbsent(method, this::getParameterNames);
+    }
+
+    private List<String> getParameterNames(Executable executable) {
+        Parameter[] parameters = executable.getParameters();
```
Comment (clone1612) [inline belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProvider.java:42]: Wouldn't a stream be more compact?

```
        return Arrays.stream(executable.getParameters())
                .map(this::getParameterName)
                .collect(Collectors.toList());
```

File: belgif-rest-problem-java-ee/src/test/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProviderTest.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import javax.ws.rs.PathParam;
+import javax.ws.rs.QueryParam;
+
+import org.junit.jupiter.api.Test;
+import org.junit.jupiter.params.ParameterizedTest;
+import org.junit.jupiter.params.provider.ValueSource;
+
+class JaxRsParameterNameProviderTest {
+
+    private JaxRsParameterNameProvider provider = new JaxRsParameterNameProvider();
```
Comment (clone1612) [inline belgif-rest-problem-java-ee/src/test/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProviderTest.java:18]: Field may be final

File: belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscoverer.java [hunk 3]
```diff
@@ -0,0 +1,61 @@
...
+        return parameterNameCache.computeIfAbsent(constructor, this::getParameterNames);
+    }
+
+    @Override
+    public String[] getParameterNames(Method method) {
+        return parameterNameCache.computeIfAbsent(method, this::getParameterNames);
+    }
+
+    private String[] getParameterNames(Executable executable) {
+        Parameter[] parameters = executable.getParameters();
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscoverer.java:35]: Wouldn't a stream be a bit more compact?

```
        return Arrays.stream(executable.getParameters())
                .map(this::getParameterName)
                .toArray(String[]::new);
```

File: belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscovererTest.java [hunk 4]
```diff
@@ -0,0 +1,61 @@
...
+import org.junit.jupiter.params.provider.ValueSource;
+import org.springframework.web.bind.annotation.CookieValue;
+import org.springframework.web.bind.annotation.MatrixVariable;
+import org.springframework.web.bind.annotation.PathVariable;
+import org.springframework.web.bind.annotation.RequestHeader;
+import org.springframework.web.bind.annotation.RequestParam;
+
+class AnnotationParameterNameDiscovererTest {
+
+    private AnnotationParameterNameDiscoverer discoverer = new AnnotationParameterNameDiscoverer();
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscovererTest.java:16]: Field can be made final

File: belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/ProblemValidatorConfigurationTest.java [hunk 5]
```diff
@@ -0,0 +1,23 @@
...
+
+import org.junit.jupiter.api.Test;
+import org.junit.platform.commons.util.ReflectionUtils;
+import org.mockito.Mockito;
+import org.springframework.context.ApplicationContext;
+import org.springframework.validation.beanvalidation.LocalValidatorFactoryBean;
+
+class ProblemValidatorConfigurationTest {
+
+    private ProblemValidatorConfiguration config = new ProblemValidatorConfiguration();
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/ProblemValidatorConfigurationTest.java:13]: Field can be made final

File: belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/ProblemValidatorConfigurationTest.java [hunk 6]
```diff
@@ -0,0 +1,23 @@
...
+
+    @Test
+    void defaultValidator() throws Exception {
+        LocalValidatorFactoryBean validator = config.defaultValidator(Mockito.mock(ApplicationContext.class));
+        Object parameterNameDiscoverer = ReflectionUtils
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/ProblemValidatorConfigurationTest.java:18]: No need to use any reflection utils, AssertJ can already handle this scenario:

```
        assertThat(validator)
                .extracting("parameterNameDiscoverer")
                .isInstanceOf(AnnotationParameterNameDiscoverer.class);
```

**Review by clone1612 — CHANGES_REQUESTED** [review]
Additional question: do we keep using `<maven.compiler.parameters>true</maven.compiler.parameters>`?

**Comment by jpraet** [comment]
> Additional question: do we keep using `<maven.compiler.parameters>true</maven.compiler.parameters>`?

I prefer to keep it, yes. I think it's a good practice. I wonder why it's not enabled by default actually.

When there is no annotation, the ParameterNameProvider/Discoverer falls back to the parameter name.

Also: for the Spring MVC annotations, the name in the annotation is actually optional. So there, we should also fall back to the parameter name, which I overlooked in the current implementation.

File: belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProvider.java [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+
+/**
+ * A ParameterNameProvider that retrieves the parameter name from JAX-RS annotations (if present).
+ *
+ * @see ParameterNameProvider
+ */
+@Provider
+public class JaxRsParameterNameProvider implements ParameterNameProvider {
+
+    private final ConcurrentHashMap<Executable, List<String>> parameterNameCache = new ConcurrentHashMap<>();
```
Comment (jpraet) [inline belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProvider.java:29]: Maybe we should make this cache static? Because I don't know if the JAX-RS / Bean Validation spec defines that there will only be a single reused instance of the ParameterNameProvider.

Comment (clone1612) [reply belgif-rest-problem-java-ee/src/main/java/io/github/belgif/rest/problem/jaxrs/JaxRsParameterNameProvider.java:29]: The interface documentation mentions that the implementation should be thread-safe, so I assume it would be reused? It wouldn't hurt to make it static though, that way we're certain.

**Comment by clone1612** [comment]
> > Additional question: do we keep using `<maven.compiler.parameters>true</maven.compiler.parameters>`?
> 
> I prefer to keep it, yes. I think it's a good practice. I wonder why it's not enabled by default actually.
> 
> When there is no annotation, the ParameterNameProvider/Discoverer falls back to the parameter name.

Ok, but wouldn't it be better to then document that best practice in the documentation?

File: belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscoverer.java [hunk 8]
```diff
@@ -0,0 +1,63 @@
...
+                .map(this::getParameterName)
+                .toArray(String[]::new);
+    }
+
+    private String getParameterName(Parameter parameter) {
+        Annotation[] annotations = parameter.getAnnotations();
+        String parameterName = null;
+        for (Annotation annotation : annotations) {
+            if (annotation instanceof RequestParam) {
+                parameterName = ((RequestParam) annotation).value();
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/main/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscoverer.java:46]: Shouldn't we break upon encountering a parameter annotation? Now we'll traverse all annotations on the parameter, including all the validations ones (if present).

Or not worth the uglier code as result will be cached?

File: belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscovererTest.java [hunk 9]
```diff
@@ -0,0 +1,66 @@
...
+        void requestHeader(@RequestHeader("name") String x) {
+        }
+
+        void cookieValue(@CookieValue("name") String x) {
+        }
+
+        void matrixVariable(@MatrixVariable("name") String x) {
+        }
+
+        void fallback(@RequestParam String name) {
```
Comment (clone1612) [inline belgif-rest-problem-spring/src/test/java/io/github/belgif/rest/problem/spring/AnnotationParameterNameDiscovererTest.java:61]: I would add an equivalent integration test for this to verify the fallback works in an actual application

**Review by clone1612 — CHANGES_REQUESTED** [review]

**Review by clone1612 — APPROVED** [review]

**Comment by jpraet** [comment]
wrong button
