### PR TITLE
Disable stacktrace on Problem exceptions

### LINKED ISSUE #278: Disable stacktrace on Problem exceptions
Java exceptions are expensive. Especially [constructing](https://www.baeldung.com/java-exceptions-performance#3-creating-an-exception-without-throwing-it) them and initializing their stacktrace.

The rest-problem-java library treats problems as exceptions (Problem extends RuntimeException). Typically, the problems are thrown only to have them then converted to a proper "application/problem+json" response. The stacktrace is not really necessary.

This [overloaded Throwable constructor](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#Throwable-java.lang.String-java.lang.Throwable-boolean-boolean-) accepts a writableStackTrace boolean flag:

> If the writable stack trace is false, this constructor will not call [fillInStackTrace()](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#fillInStackTrace--), a null will be written to the stackTrace field, and subsequent calls to fillInStackTrace and [setStackTrace(StackTraceElement[])](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#setStackTrace-java.lang.StackTraceElement:A-) will not set the stack trace. If the writable stack trace is false, [getStackTrace()](https://docs.oracle.com/javase/8/docs/api/java/lang/Throwable.html#getStackTrace--) will return a zero length array.

So we could set this flag to false for a performance gain.

If necessary, we could add a `io.github.belgif.rest.problem.stacktrace-disabled` flag (default true) which allows users to opt-out if they do want their problem exceptions to have a stacktrace.

### PR DESCRIPTION
**Pull request by jpraet**
Fixes #278

### CODE REVIEW

File: belgif-rest-problem/src/test/java/io/github/belgif/rest/problem/api/ProblemTest.java [hunk 1]
```diff
@@ -113,7 +115,28 @@ void getMessage() {
...
+    }
+
+    @Test
+    void stackTraceDisabled() {
+        try {
+            ProblemConfig.setStackTraceEnabled(false);
+            Problem problem = new MyProblem();
+            assertThat(problem.getStackTrace()).isEmpty();
+        } finally {
+            ProblemConfig.reset();
```
Comment (usku01) [inline belgif-rest-problem/src/test/java/io/github/belgif/rest/problem/api/ProblemTest.java]: maybe we should add a single 'reset'  unit test to make sure that all default values are what we expect after the reset?
